In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [2]:
# Load Titanic
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
print(df.shape)
print(df.head())

(891, 12)
   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [3]:
df = df[['Survived', 'Pclass', 'Sex', 'Age', 'Fare']]

In [4]:
df

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [5]:
df['Age']= df['Age'].fillna(df['Age'].median())

In [6]:
df['Sex']= df['Sex'].map({'male':1, 'female':0})
print(df.head())
print(df.isnull().sum())

   Survived  Pclass  Sex   Age     Fare
0         0       3    1  22.0   7.2500
1         1       1    0  38.0  71.2833
2         1       3    0  26.0   7.9250
3         1       1    0  35.0  53.1000
4         0       3    1  35.0   8.0500
Survived    0
Pclass      0
Sex         0
Age         0
Fare        0
dtype: int64

In [8]:
X = df[['Pclass', 'Sex', 'Age', 'Fare']]
Y = df['Survived']

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [10]:
print("Training size:",  X_train.shape)
print("Testing size:", X_test.shape)

Training size: (712, 4)
Testing size: (179, 4)

In [11]:
#fluid and train the model
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=42)

In [14]:
#test model
predictions = model.predict(X_test)
#check accuracy
accuracy = accuracy_score(Y_test, predictions)
print("Model Accuracy ", round(accuracy * 100,2), "%")

Model Accuracy  74.86 %

In [15]:
# Let's predict - will this person survive?
# Pclass=3, Sex=male(1), Age=22, Fare=7.25
person = [[3, 1, 22, 7.25]]
result = model.predict(person)

if result[0] == 1:
    print("This person SURVIVES! ✅")
else:
    print("This person does NOT survive ❌")

This person does NOT survive ❌

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [16]:
# Pclass=3, Sex=male(1), Age=22, Fare=7.25
person = [[3, 0, 22, 7.25]]
result = model.predict(person)

if result[0] == 1:
    print("This person SURVIVES! ✅")
else:
    print("This person does NOT survive ❌")

This person SURVIVES! ✅

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [17]:
# Person 1 - Rich female, 1st class
person1 = [[1, 0, 25, 100]]
print("Person 1:", model.predict(person1))

# Person 2 - Poor male, 3rd class
person2 = [[3, 1, 25, 7]]
print("Person 2:", model.predict(person2))

Person 1: [0]
Person 2: [0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [18]:
# Person 1 - Male, 3rd class, age 22
person1 = [[3, 1, 22, 7.25]]

# Person 2 - Female, 3rd class, age 22
person2 = [[3, 0, 22, 7.25]]

print("Male 3rd class:", model.predict(person1))
print("Female 3rd class:", model.predict(person2))

# Now try 1st class female
person3 = [[1, 0, 22, 100]]
print("Female 1st class:", model.predict(person3))

Male 3rd class: [0]
Female 3rd class: [1]
Female 1st class: [1]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [20]:
Y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

In [22]:
from sklearn.ensemble import RandomForestClassifier

# Random Forest - stronger than Decision Tree
#Decision Tree = one person making a decision
#Random Forest = 100 people voting on a decision — majority wins!
#n_estimators= 100 means -- 100 trees coting..
model2 = RandomForestClassifier(n_estimators=100, random_state=42)
model2.fit(X_train, Y_train)

predictions2 = model2.predict(X_test)
accuracy2 = accuracy_score(Y_test, predictions2)

print("Decision Tree accuracy:", round(accuracy * 100, 2), "%")
print("Random Forest accuracy:", round(accuracy2 * 100, 2), "%")

Decision Tree accuracy: 74.86 %
Random Forest accuracy: 80.45 %

In [24]:
print("""
TITANIC SURVIVAL PREDICTION - ML MODEL
=======================================
Algorithm 1: Decision Tree - 74.86% accuracy
Algorithm 2: Random Forest - 80.45% accuracy

Key findings:
- Gender is the strongest survival predictor
- 3rd class males had lowest survival chance
- Random Forest outperforms Decision Tree by 5.59%

Dataset: Titanic (891 rows)
Tools: Python, Pandas, Scikit-learn
Author: Ayesha Sultana
""")

TITANIC SURVIVAL PREDICTION - ML MODEL
=======================================
Algorithm 1: Decision Tree - 74.86% accuracy
Algorithm 2: Random Forest - 80.45% accuracy

Key findings:
- Gender is the strongest survival predictor
- 3rd class males had lowest survival chance
- Random Forest outperforms Decision Tree by 5.59%

Dataset: Titanic (891 rows)
Tools: Python, Pandas, Scikit-learn
Author: Ayesha Sultana